(load "settree.scm")
(define (tree->list1 tree)
	(if (null? tree) '() 
		(append (tree->list1 (left-branch tree))
			 (cons (entry tree) (tree->list1(right-branch tree))))))
(define (tree->list2 tree )
	(define (copy-to-list tree result)
		(if (null? tree) result
			(copy-to-list (left-branch tree)
					 (cons (entry tree) (copy-to-list (right-branch tree) result)))))
	(copy-to-list tree '()))
