(load "settree.scm")
(define (lookupt given-key recordstree)
	(cond ((null? recordstree) #f)
		((= given-key (key (entry recordstree))) (entry recordstree))
		(( < given-key (key (entry recordstree)))
			 (lookupt given-key (left-branch recordstree)))
		(( > given-key (key (entry recordstree)))
              (lookupt given-key (right-branch recordstree)))
		(else (error "wrong type"))))
