(load "polynomial-package.scm")
;(load "scheme-number-package.scm")
;(load "rational-package.scm")
(load "raw-apply-generic.scm")
;(load "2-82-apply-generic-coercion.scm")

;(install-scheme-number-package)
;(install-rational-package)
(install-polynomial-package)
(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (=zero? x) (apply-generic '=zero? x))
