(load "simula.scm")
(define (or-gate input-1 input-2  output)
	(inverter input-1 a)
	(inverter input-2 b)
	(and-gate a b c)
	(inverter c output)
	'ok)
(define or-gate-delay (+ (* 3 inverter-delay) and-gate-delay))
(or-gate input-1 input-2 output)
