(define (make-account balance password)
	(define (withdraw x)
		(if (>= balance x) (begin (set! balance (- balance x) ) balance)
	        	"unsufficient funds"))
	(define (deposit x) 
		  (set! balance (+ balance x) )balance)
	(define (wrong-password args) (display "Incorrect password"))
	(define (dispatch m given-password)
		(if  (eq? given-password password ) 
		(cond ((eq? m 'withdraw) withdraw)
			 ((eq? m 'deposit ) deposit)
			(else (error "Unknown request")))
		(lambda (x)"Incorrect password")));; nongcuo le fuhao diaoyong shunxu
	dispatch)
(define acc (make-account 1000 'a))
