(load "probe-connector.scm")
 (load "constraint.scm")
 (load "make-connector.scm")
(define (square a b) (multiplier a a b))
(define a (make-connector))
(define b (make-connector))
(probe " A temp" a)
(probe " B temp " b)
(square a b)
