(define (make-account balance password)
	(let ((trials 0))
	(define (withdraw x)
		(if (>= balance x) (begin (set! balance (- balance x) ) balance)
	        	"unsufficient funds"))
	(define (deposit x) 
		  (set! balance (+ balance x) )balance)
	(define (wrong-password args) (display "Incorrect password"))
	(define (call-the-cops args)(display "call the police"))
	(define (dispatch m given-password)
		(if  (eq? given-password password ) 
			(cond ((eq? m 'withdraw) withdraw)
				 ((eq? m 'deposit ) deposit)
				(else (error "Unknown request")))
			(if (>= trials 2) call-the-cops
				(begin (set! trials (+ trials 1))(lambda (x) "Incorrect password")))))
	dispatch))
(define acc (make-account 1000 'a))
