(load "make-serializer.scm")
(define (make-semaphore n)
		(define (acquire)
			(if (test-and-set! n) (acquire) 'ok))
		(define (release)
			(set! n (+ n 1))
			'ok)
		(define (dispatch m)
			(cond ((eq? m 'acquire) (acquire))
				  ((eq? m 'release) (release))
				  (else (error "Unknown-mode make semaphore"))))
	dispatch)

(define (test-and-set! n)
	(if (= n 0) #t (begin (set! n (- n 1)) #f)))

