(load "make-serializer.scm")
(define (make-semaphore n)
	(let ((mutex (make-mutex)))
		(define (acquire)
			(mutex 'acquire)
			(if ( > n 0) (begin (set! n (- n 1)) (mutex 'release) 'ok)
						 (begin (mutex 'release) (acquire))))
		(define (release)
			(mutex 'acquire)
			(set! n (+ n 1))
			(mutex 'release)
			'ok)
		(define (dispatch m)
			(cond ((eq? m 'acquire) (acquire))
				  ((eq? m 'release) (release))
				  (else (error "Unknown-mode make semaphore"))))
	dispatch))

