(load "monte-carlo.scm")
(define (estimate-intergral-p x1 x2 y1 y2 trials)
	(define (P?)
		(<  (+ (square (- (random-in-range x1 x2) 5) )	
				(square(- (random-in-range y1 y2) 7 ))) 9.0))
	(monte-carlo trials P?))
(define (random-in-range low high)
	(let ((range (- high low)))
	(+ (random range) low)))
(define f (estimate-intergral-p 2.0 8.0 4.0 10.0 1000))
