(load "3-59.scm")
(define (mul-series s1 s2)
	 (cons-stream (* (stream-car s1) (stream-car s2)) 
		 (add-streams (scale-stream (stream-cdr s1) (stream-car s2))
					  (mul-series s1 (stream-cdr s2)))))
;(display-stream (stream-section (mul-series cosine-series sine-series)  0  10))
(define sin2 (mul-series sine-series sine-series))
(define cos2 (mul-series cosine-series cosine-series))
(define sum (add-streams sin2 cos2))
;(display-stream (stream-section sum  0  10))
