(define(general-solve-2nd f y0 dy0 dt) 
         (define y (integral (delay dy) y0 dt)) 
         (define dy (integral (delay ddy) dy0 dt)) 
         (define ddy (stream-map f dy y)) 
         y)
;(stream-ref (general-solve-2nd  (lambda (y t) (+ t (log y))) 10.2 19.34 0.01) 100) 
